.\" Copyright (c)2011 Laurence Tratt <http://tratt.net/laurie>
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a
.\" copy of this software and associated documentation files (the
.\" "Software"), to deal in the Software without restriction, including
.\" without limitation the rights to use, copy, modify, merge, publish,
.\" distribute, sublicense, and/or sell copies of the Software, and to
.\" permit persons to whom the Software is furnished to do so, subject to the
.\" following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included
.\" in all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
.\" OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
.\" NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
.\" DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
.\" OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
.\" USE OR OTHER DEALINGS IN THE SOFTWARE.
.Dd $Mdocdate: February 17 2020 $
.Dt SUPUNER 1
.Os
.Sh NAME
.Nm supuner
.Nd SUPress stdout / stderr UNless ERror
.Sh SYNOPSIS
.Nm supuner
.Op Fl e
.Op Fl o Ar file
.Ar command
.Op Ar options ...
.Sh DESCRIPTION
.Nm
executes a command and manipulates its stderr and stdout.
By default, it captures both stderr and stdout and only outputs their combined
value to stdout if
.Ar command
fails.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl e
If
.Fl o
is specified, then as well as sending output to a file, echo stdout
and stderr combined to stdout.
.It Fl o Ar file
Send stdout and stderr to
.Ar file .
.El
.Pp
.Nm
exits with the exit code of
.Ar command .
.Sh EXAMPLES
Here are examples of the basic styles of use of
.Nm :
.Pp
.Dl $ supuner ls /bin/sh
.Dl $ supuner ls /bin/sh /doesntexist
.Dl ls: /doesntexist: No such file or directory
.Dl /bin/sh
.Dl $ supuner -o /tmp/o ls /bin/sh /doesntexist
.Dl $ echo $?
.Dl 1
.Dl $ cat /tmp/o
.Dl ls: /doesntexist: No such file or directory
.Dl /bin/sh
.Dl $ supuner -e -o /tmp/o ls /bin/sh /doesntexist
.Dl ls: /doesntexist: No such file or directory
.Dl /bin/sh
.Dl $ echo $?
.Dl 1
.Dl $ cat /tmp/o
.Dl ls: /doesntexist: No such file or directory
.Dl /bin/sh
.Pp
Using the fact that
.Nm
exits with the exit code of
.Ar command ,
one can use the
.Ql ||
operator to perform actions on the combined stdout / stderr output, for example:
.Bd -literal -offset 4n
supuner -o /tmp/o ls /bin/sh /doesntexist >2 /dev/null \\
  || mail -s 'Error from ls' somebody@something.com < /tmp/o
.Ed
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Laurence Tratt
.Lk https://tratt.net/laurie/ .
